name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating an issue. You will hear back from the `code owners` shortly. If this is a user story, please ignore this automated message."
        pr-message: "Your pull request will be monitored and the automated tests will conducted for any failure. You will hear back from the `code owners` shortly."
